### PR TITLE
cassandra workshop/labs

### PR DESCRIPTION
**Pull request by TheovanKraay**

### CODE REVIEW

**Comment by aliuy** [comment]
Ooo thanks Theo!

Can you turn on GitHub Pages on your fork to see how well the markdown renders?

image

**Comment by TheovanKraay** [comment]
https://theovankraay.github.io/labs-1/

**Comment by aliuy** [comment]
Thanks Theo - skimming through this is great content!

One nit that I wish we had done with the other labs (we can update those too) in the Pre-lab is to disclose a ballpark / estimated spend per day for the lab (to avoid accidental billing surprises).

@markjbrown @anfeldma-ms  - mind doing a quick review?

**Review by aliuy — APPROVED** [review]

**Comment by TheovanKraay** [comment]
Thanks, main credits to Abhishek (Cloud Developer Advocate) who developed a large majority of the content from my asks :-)

**Comment by markjbrown** [comment]
This is impressive Theo. Looks good to me. No changes from my end.

btw, I'm looking to add a modeling and partitioning lab to our .NET workshop labs to use a single dataset derived from Adventure Works database. Let me know if you'd be interested in leveraging this in this Cassandra version at some point in the future.

Thanks.

**Review by markjbrown — APPROVED** [review]

**Comment by TheovanKraay** [comment]
Thanks all, @anfeldma-ms anything to add?

**Review by anfeldma-ms — APPROVED** [review]

**Review by anfeldma-ms — APPROVED** [review]

**Pull request merged**
